### ISSUE TITLE
Viewing style guide just renders .lsg file as markdown.

### ISSUE THREAD

**Issue by jmcnevin** [hagenburger/livingstyleguide#113]
This is with the 'v2' branch, commit: '4852c8b', sass-rails 5.0.1, and rails 4.2

I'm not sure if I'm doing something wrong here, but with a /app/assets/stylesheets/styleguide.html.lsg like the following:

```
source: 'style.scss'
title: 'Living Style Guide'
```

Upon viewing /assets/styleguide.html, I just see the lsg file rendered as markdown inside of the default LSG layout, with nothing else pulled in from *.md files inside my stylesheets directory.

**Comment by hagenburger** [comment]
**This is an early alpha version which is in the middle of development.** For your examples, the current state is:

* The [Yaml syntax is deprecated for v2. It’s using `@filter` everywhere](http://www.hagenburger.net/BLOG/livingstyleguide-2.html).
* Automated importing of _*.md_ files is not upgraded to v2 yet.
* `@title` also is not upgraded yet.
* Within Rails, the path must be relative to the Rails.root.

You can try this for now:

```
@import app/assets/stylesheets/style.scss
@import app/assets/stylesheets/components
```

The first line imports the Sass source into the style guide (but only the Sass, not any matching _*.md_ file as current stable v1 does).

The second line for example imports all _*.lsg_ files from the components directory (v2 uses _.lsg_ instead of _.md_ as extension as the syntax offers filters on top of Markdown).

You can have a look at <https://github.com/hagenburger/livingstyleguide-concept/blob/master/c_new-multiple-pages-v2.0x/pages.html.lsg> (and other files in that repository).

There will be new alpha versions soon (next one maybe tomorrow). Let me know, if you have any question!

**Comment by jmcnevin** [comment]
Thanks for the explanation!  Looking forward to the new features!

**Comment by wouter-muller** [comment]
I am on "2.0.0.pre.1" and experiencing the same issue
